[package]
name = "kmscube-rs"
version = "0.1.0"
authors = ["kosyak <vadim@kosov.eu>"]
edition = "2018"

[dependencies]
gbm = { git = "https://github.com/kosyak/gbm.rs.git", branch = "master" }
drm = { git = "https://github.com/kosyak/drm-rs.git", branch = "master" }
sys = { path = "sys" }
